/*
 * ShopManagerPatch.cs
 *  
 * The shop manager manages item generation and cart management/purchase logic (WIP)
 */

using HarmonyLib;
using System.Collections.Generic;
using UnityEngine;

namespace SkillFern.Patches
{
    [HarmonyPatch(typeof(ShopManager))]
    public class ShopManagerPatch
    {
        /*
         * Removes item upgrades from the shop by clearing the list generated by the StatManager
         */
        [HarmonyPatch("GetAllItemsFromStatsManager")]
        [HarmonyPostfix]
        static void RemoveItemUpgrades(ref List<Item> ___potentialItemUpgrades) {
            // clear the pool of upgrades to draw from
            ___potentialItemUpgrades.Clear();
        }

    }
}
