/*
 * ShopManagerPatch.cs
 *  
 * The shop manager manages item generation and cart management/purchase logic
 */

using HarmonyLib;
using SkillFern.Utilities;
using System.Collections.Generic;
using UnityEngine;

namespace SkillFern.Patches
{
    [HarmonyPatch(typeof(ShopManager))]
    public class ShopManagerPatch
    {
        /*
         * AFTER ShopManager.GetAllItemsFromStatsManager
         * 
         * Removes item upgrades from the shop by clearing the list generated by the StatManager
         */
        [HarmonyPatch("GetAllItemsFromStatsManager")]
        [HarmonyPostfix]
        static void RemoveItemUpgrades(ref List<Item> ___potentialItemUpgrades) {
            // clear the pool of upgrades to draw from (if enabled in config)
            if (ConfigHelper.ShopUpgradesDisabled())
                ___potentialItemUpgrades.Clear();

            // add skill cubes if enabled in config
            if (ConfigHelper.SkillPointsPurchaseable()) {
                ShopHelper.SpawnSkillCubes(___potentialItemUpgrades);
            }
        }

    }
}
